export const typography = {
  fontFamily: {
    primary: 'Plus Jakarta Sans',
    secondary: 'SF Pro Text',
    default: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei", "Source Han Sans CN", sans-serif',
  },
  fontWeights: {
    regular: '400',
    medium: '500',
    semiBold: '600',
    bold: '700',
  },
  sizes: {
    h1: 32,
    h2: 24,
    h3: 20,
    h4: 18,
    h5: 16,
    h6: 14,
    body1: 16,
    body2: 14,
    caption: 12,
    button: 16,
  },
  lineHeights: {
    h1: 40,
    h2: 32,
    h3: 28,
    h4: 24,
    h5: 24,
    h6: 20,
    body1: 24,
    body2: 20,
    caption: 16,
    button: 24,
  },
  styles: {
    h1: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 32,
      lineHeight: 40,
      fontWeight: '700',
    },
    h2: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 24,
      lineHeight: 32,
      fontWeight: '700',
    },
    h3: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 20,
      lineHeight: 28,
      fontWeight: '600',
    },
    h4: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600',
    },
    h5: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    h6: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
    },
    body1: {
      fontFamily: 'SF Pro Text',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '400',
    },
    body2: {
      fontFamily: 'SF Pro Text',
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
    },
    caption: {
      fontFamily: 'SF Pro Text',
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '400',
    },
    button: {
      fontFamily: 'SF Pro Text',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
      textTransform: 'none',
    },
  },
  shadows: {
    none: {
      shadowColor: 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 4,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 6,
    },
  },
};
